#!/usr/bin/env python3
"""Generate docs/commands.md from the skills. Accurate by construction, kept in sync."""
import glob, yaml, sys, os

os.chdir(os.path.join(os.path.dirname(__file__), '..'))

# slug -> category. Categories render in this order.
GROUPS = [
    ("Core modules", [
        "setup", "memory", "operator", "optimizer", "team", "client", "connect"]),
    ("Daily operations", [
        "daily", "weekly-review", "business-review", "pipeline-update",
        "meeting-capture", "project-update", "content-plan", "sop-create", "exec-dashboard"]),
    ("SEO and visibility", [
        "seo-audit", "seo-optimize", "seo-schema", "seo-programmatic", "seo-compare", "geo-optimize"]),
    ("Sales and pipeline", [
        "lead-research", "lead-qualify", "lead-enrich", "crm-mining", "pipeline-review", "win-loss"]),
    ("Content and publishing", [
        "email-sequence", "email-personalize", "social-post", "newsletter", "blog-post",
        "landing-page", "repurpose", "wp-publish", "wp-refresh"]),
    ("Retention and proof", [
        "customer-onboarding", "churn-watch", "case-study", "testimonial", "portfolio-watch"]),
    ("Ads and acquisition", ["ads-audit", "free-audit"]),
]

NOTES = {
    "Core modules": "Needs: `/setup` needs only an empty folder. The rest need a vault. Produces: the vault, the memory ledger, daily runs, audits, team and client structure, connectors.",
    "Daily operations": "Needs: a vault. Produces: daily notes, weekly and monthly reviews, an updated pipeline, an HTML dashboard. Each run that moves a metric appends one ledger row.",
    "SEO and visibility": "Needs: a vault and a target URL. Produces: drafts and prioritized findings in `Projects/` or `Content/`, plus ledger rows. Draft only. Never touches the live site.",
    "Sales and pipeline": "Needs: a vault and `Pipeline/` data, or a CRM export. Produces: prospect profiles, fit verdicts, pipeline analysis. No outreach is sent.",
    "Content and publishing": "Needs: a vault, your offers, your ICP, and your brand voice. Produces: drafts in `Content/`. Draft only. `wp-publish` and `wp-refresh` stage WordPress drafts, never live.",
    "Retention and proof": "Needs: a vault and customer or client data. Produces: onboarding plans, churn-risk lists, case studies drawn from the ledger, testimonials, a portfolio roll-up.",
    "Ads and acquisition": "Needs: an ad-account export or a described setup, or a prospect URL. Produces: a prioritized findings report. Draft only. Never changes budgets or bids.",
}

# load skill descriptions
desc = {}
for f in sorted(glob.glob('skills/*/SKILL.md')):
    parts = open(f).read().split('---', 2)
    m = yaml.safe_load(parts[1]) or {}
    desc[m['name']] = m['description'].replace('|', r'\|')

placed = set()
total = len(desc)

lines = []
lines.append("# Command Reference")
lines.append("")
lines.append(f"_{total} commands. Generated by `scripts/gen-commands.py`. Do not hand-edit._")
lines.append("")
lines.append("Every command is a Claude skill. Type the command, or describe what you want in plain words and Conversion OS routes to the right one. Every command is draft only on anything outbound: it writes drafts, a human sends and publishes.")
lines.append("")
lines.append("New here? Read `docs/getting-started.md` first, then run `/setup`.")
lines.append("")

for group, slugs in GROUPS:
    present = [s for s in slugs if s in desc]
    if not present:
        continue
    lines.append(f"## {group}")
    lines.append("")
    lines.append(NOTES.get(group, ""))
    lines.append("")
    lines.append("| Command | What it does |")
    lines.append("|---------|--------------|")
    for s in present:
        lines.append(f"| `/{s}` | {desc[s]} |")
        placed.add(s)
    lines.append("")

leftover = sorted(set(desc) - placed)
if leftover:
    lines.append("## Other")
    lines.append("")
    lines.append("| Command | What it does |")
    lines.append("|---------|--------------|")
    for s in leftover:
        lines.append(f"| `/{s}` | {desc[s]} |")
    lines.append("")

open('docs/commands.md', 'w').write("\n".join(lines).rstrip() + "\n")
print(f"  OK: docs/commands.md written ({total} commands, {len(leftover)} ungrouped)")
