#!/usr/bin/env bash
# Validate all skills, (re)generate SKILLS.md, and run every gate.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT"

echo "== validate skills + generate SKILLS.md =="
python3 - <<'PY'
import glob, yaml, sys
rows=[]; bad=0
for f in sorted(glob.glob('skills/*/SKILL.md')):
    parts=open(f).read().split('---',2)
    try:
        m=yaml.safe_load(parts[1]) or {}
        name=m['name']; desc=m['description']
        assert isinstance(desc,str) and '\n' not in desc and ':' not in desc, "bad description"
        rows.append((name,desc))
    except Exception as e:
        bad+=1; print(f"  INVALID {f}: {e}")
if bad: sys.exit(1)
core=['setup','memory','operator','optimizer','team','client','connect']
with open('SKILLS.md','w') as out:
    out.write('# Conversion Skills\n\n')
    out.write(f'_{len(rows)} skills. Generated by `scripts/sync-skills.sh`. Do not hand-edit._\n\n')
    out.write('## Core modules\n\n')
    for n,d in rows:
        if n in core: out.write(f'- **`/{n}`** · {d}\n')
    out.write('\n## Workflow Library\n\n')
    for n,d in rows:
        if n not in core: out.write(f'- **`/{n}`** · {d}\n')
print(f"  OK: {len(rows)} skills validated, SKILLS.md written")
PY
python3 "$ROOT/scripts/gen-commands.py"

# guard: no stray SKILL.md outside skills/
stray="$(find . -name 'SKILL.md' -not -path './skills/*' -not -path './.git/*' 2>/dev/null; find . -maxdepth 1 -name '*-SKILL.md' 2>/dev/null)"
if [ -n "$stray" ]; then echo "FAIL: stray SKILL files outside skills/:"; echo "$stray"; exit 1; fi

echo "== run gates =="
"$ROOT/scripts/lint-cleanroom.sh"
"$ROOT/scripts/check-budgets.sh"
"$ROOT/scripts/scan-secrets.sh"
"$ROOT/scripts/check-firewall.sh"
"$ROOT/scripts/check-brand.sh"
echo "== all checks passed =="
